version: "3.2"

services:

  frontend:
    build: ./frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - 80:3001
    depends_on: 
      - backend

  backend: 
    build: ./backend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./backend:/app    
    ports: 
      - 3001:3000
